// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function length($$window) {
  var localStorage = $$window.localStorage;
  if (localStorage !== undefined) {
    return Caml_option.some(localStorage.length);
  }
  
}

function clear($$window) {
  var localStorage = $$window.localStorage;
  if (localStorage !== undefined) {
    return Caml_option.some(Curry._1(localStorage.clear, undefined));
  }
  
}

function key($$window, idx) {
  var localStorage = $$window.localStorage;
  if (localStorage !== undefined) {
    return Caml_option.some(Curry._1(localStorage.key, idx));
  }
  
}

function getItem($$window, key) {
  var localStorage = $$window.localStorage;
  if (localStorage === undefined) {
    return ;
  }
  try {
    return Caml_option.some(Curry._1(localStorage.getItem, key));
  }
  catch (exn){
    return ;
  }
}

function removeItem($$window, key) {
  var localStorage = $$window.localStorage;
  if (localStorage !== undefined) {
    return Caml_option.some(Curry._1(localStorage.removeItem, key));
  }
  
}

function setItem($$window, key, value) {
  var localStorage = $$window.localStorage;
  if (localStorage !== undefined) {
    return Caml_option.some(Curry._2(localStorage.setItem, key, value));
  }
  
}

exports.length = length;
exports.clear = clear;
exports.key = key;
exports.getItem = getItem;
exports.removeItem = removeItem;
exports.setItem = setItem;
/* No side effect */
