// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function style(n) {
  return n.style;
}

function getStyle(n, key) {
  return n.style[key];
}

function setStyle(n, key, value) {
  n.style[key] = value;
}

function setStyleProperty(n, priorityOpt, key, value) {
  var priority = priorityOpt !== undefined ? priorityOpt : false;
  var style = n.style;
  var _valid = style.setProperty;
  if (_valid !== undefined) {
    return style.setProperty__(key, value, priority ? "important" : null);
  } else {
    return setStyle(n, key, value);
  }
}

function childNodes(n) {
  return n.childNodes;
}

function firstChild(n) {
  return n.firstChild;
}

function appendChild(n, child) {
  return Curry._1(n.appendChild, child);
}

function removeChild(n, child) {
  return Curry._1(n.removeChild, child);
}

function insertBefore(n, child, refNode) {
  return Curry._2(n.insertBefore, child, refNode);
}

function remove(n, child) {
  return Curry._1(n.remove, child);
}

function setAttributeNS(n, namespace, key, value) {
  return Curry._3(n.setAttributeNS, namespace, key, value);
}

function setAttribute(n, key, value) {
  return Curry._2(n.setAttribute, key, value);
}

function setAttributeNsOptional(n, namespace, key, value) {
  if (namespace === "") {
    return Curry._2(n.setAttribute, key, value);
  } else {
    return Curry._3(n.setAttributeNS, namespace, key, value);
  }
}

function removeAttributeNS(n, namespace, key) {
  return Curry._2(n.removeAttributeNS, namespace, key);
}

function removeAttribute(n, key) {
  return Curry._1(n.removeAttribute, key);
}

function removeAttributeNsOptional(n, namespace, key) {
  if (namespace === "") {
    return Curry._1(n.removeAttribute, key);
  } else {
    return Curry._2(n.removeAttributeNS, namespace, key);
  }
}

function addEventListener(n, typ, listener, options) {
  return Curry._3(n.addEventListener, typ, listener, options);
}

function removeEventListener(n, typ, listener, options) {
  return Curry._3(n.removeEventListener, typ, listener, options);
}

function focus(n) {
  return Curry._1(n.focus, undefined);
}

function set_nodeValue(n, text) {
  n.nodeValue = text;
}

function get_nodeValue(n) {
  return n.nodeValue;
}

function remove_polyfill(param) {
  ((// remove polyfill
  (function() {
    if (!('remove' in Element.prototype)) {
      Element.prototype.remove = function() {
        if (this.parentNode) {
          this.parentNode.removeChild(this);
        }
      };
    };
  }())));
}

exports.style = style;
exports.getStyle = getStyle;
exports.setStyle = setStyle;
exports.setStyleProperty = setStyleProperty;
exports.childNodes = childNodes;
exports.firstChild = firstChild;
exports.appendChild = appendChild;
exports.removeChild = removeChild;
exports.insertBefore = insertBefore;
exports.remove = remove;
exports.setAttributeNS = setAttributeNS;
exports.setAttribute = setAttribute;
exports.setAttributeNsOptional = setAttributeNsOptional;
exports.removeAttributeNS = removeAttributeNS;
exports.removeAttribute = removeAttribute;
exports.removeAttributeNsOptional = removeAttributeNsOptional;
exports.addEventListener = addEventListener;
exports.removeEventListener = removeEventListener;
exports.focus = focus;
exports.set_nodeValue = set_nodeValue;
exports.get_nodeValue = get_nodeValue;
exports.remove_polyfill = remove_polyfill;
/* No side effect */
